"""Albert (CIS/MS-ISAC network monitoring) alert export ingestion.

Parses the .xlsx "Alert Detail" exports produced by the CIS Portal's ANET
(Albert NetFlow Extract Tool) reporting feature and stores each row as a
normalized alert record for trend analysis and IOC cross-referencing.

Column layout confirmed against a real "Whitelisted_Albert_Alert_Detail" export:
TIME (GMT), DEVICE, ALERT MESSAGE, SOURCE IP, DESTINATION IP, SOURCE PORT,
DESTINATION PORT, PROTOCOL, STREAM DATA HEX, STREAM DATA, STREAM DATA LENGTH.
CIS produces other report variants (e.g. a full/all-alerts export, or a blocked-
alerts export) under different sheet names but -- as far as this one sample shows
-- the same column layout, so the parser reads whichever sheet is present rather
than hardcoding "Whitelisted_...", and infers a best-effort "disposition" label
from the sheet/file name (it is a label, not a guarantee CIS won't change it).

Albert's raw export carries no severity or category field of its own -- it's a
flat IDS/Suricata-style alert message string. ALERT_KNOWLEDGE below maps the
alert message patterns actually observed in a real export to a plain-English
explanation, a severity, and a rough MITRE ATT&CK technique. This list is meant
to grow over time as more signatures are seen in real exports -- an unrecognized
message gets a generic, clearly-labeled fallback explanation rather than a
guessed-and-possibly-wrong one.
"""
import io
import ipaddress
import re
import uuid
from datetime import datetime, timezone, timedelta
from typing import Optional

PROTOCOL_NAMES = {1: "ICMP", 6: "TCP", 17: "UDP"}

REQUIRED_COLUMNS = {
    "TIME (GMT)", "DEVICE", "ALERT MESSAGE", "SOURCE IP", "DESTINATION IP",
    "SOURCE PORT", "DESTINATION PORT", "PROTOCOL",
}

# (pattern, {severity, explanation, mitre_technique}) -- checked in order, first
# match wins. Add new entries here as new Albert signatures show up in real
# exports; don't guess at ones that haven't actually been seen.
ALERT_KNOWLEDGE = [
    (re.compile(r"powershell.*smb|smb.*powershell", re.I), {
        "severity": "High",
        "category": "Possible Lateral Movement",
        "explanation": (
            "PowerShell activity was observed traveling over an SMB (Windows file-sharing) connection. "
            "This is a common pattern for lateral movement: an attacker who already has a foothold on one "
            "machine uses PowerShell remotely against another machine on the network, often to spread "
            "further or run commands without needing to log in interactively. Worth confirming this "
            "matches a known admin/IT activity (remote scripting, patch deployment) rather than an intruder."
        ),
        "mitre_technique": "T1021.002 (Remote Services: SMB/Windows Admin Shares), T1059.001 (PowerShell)",
    }),
    (re.compile(r"unsupported.*fake.*firefox|fake.*firefox.*version", re.I), {
        "severity": "Low",
        "category": "Suspicious Browser Identification",
        "explanation": (
            "A device sent a network request identifying itself as an old, outdated version of the Firefox "
            "browser. Real browsers auto-update and rarely present this exact identifier -- software that "
            "isn't actually a browser (update checkers, ad/tracking libraries, or occasionally malware) "
            "sometimes reuses an old browser identifier to blend in with normal web traffic. Usually low-risk "
            "on its own, but worth checking what software on the source device is actually making these calls."
        ),
        "mitre_technique": "T1036 (Masquerading)",
    }),
    (re.compile(r"known external ip lookup service", re.I), {
        "severity": "Low",
        "category": "External IP Lookup",
        "explanation": (
            "A device on the network reached out to a service that reports back the caller's public IP "
            "address (similar to a \"what's my IP\" site). This is usually harmless network diagnostic "
            "behavior from legitimate software, but it's also a step malware sometimes takes early on to "
            "confirm outbound internet connectivity and learn its own external IP."
        ),
        "mitre_technique": None,
    }),
]

_FALLBACK_KNOWLEDGE = {
    "severity": "Medium",
    "category": "Uncategorized",
    "mitre_technique": None,
}


def _explain_alert(message: str) -> dict:
    for pattern, info in ALERT_KNOWLEDGE:
        if pattern.search(message or ""):
            return info
    return {
        **_FALLBACK_KNOWLEDGE,
        "explanation": (
            f"This alert (\"{message}\") was generated by an Albert sensor's intrusion detection signature. "
            "VulnOps doesn't have a plain-English description for this specific signature yet -- treat it as "
            "Medium severity by default until reviewed, and check the CIS ANET portal or your MS-ISAC analyst "
            "for signature details."
        ),
    }


def _parse_time_gmt(raw) -> Optional[str]:
    """Parses Albert's "7/13/2026 5:59:53 AM GMT " format into an ISO8601 UTC
    string. Also tolerates a native datetime, which openpyxl returns directly for
    some date-formatted cells regardless of the display string."""
    if raw is None:
        return None
    if isinstance(raw, datetime):
        dt = raw if raw.tzinfo else raw.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc).isoformat()
    s = re.sub(r"\s*GMT\s*$", "", str(raw).strip(), flags=re.I).strip()
    for fmt in ("%m/%d/%Y %I:%M:%S %p", "%m/%d/%Y %H:%M:%S", "%m/%d/%Y %I:%M %p"):
        try:
            return datetime.strptime(s, fmt).replace(tzinfo=timezone.utc).isoformat()
        except ValueError:
            continue
    return None


def _infer_disposition(filename: str, sheet_name: str) -> str:
    combined = f"{filename} {sheet_name}".lower()
    if "whitelist" in combined or "allowlist" in combined:
        return "allowlisted"
    if "block" in combined:
        return "blocked"
    return "flagged"


_NONPRINTABLE_RUN_RE = re.compile(r"[^\x09\x0A\x0D\x20-\x7E]+")


def _clean_stream_data(raw):
    """Albert's STREAM DATA column is the raw captured payload verbatim --
    perfectly readable for HTTP/plaintext protocols, but SMB and other binary
    protocols embed non-printable control bytes that render as mojibake in a UI
    (a wall of accented/box-drawing characters). This collapses every run of
    non-printable bytes into a single placeholder marker so the printable parts
    (commands, filenames, hostnames, headers) stay legible. The original,
    uncleaned capture is kept separately (stream_data_raw) for anyone who
    specifically wants to see the exact bytes."""
    if not raw:
        return raw
    return _NONPRINTABLE_RUN_RE.sub(" \u22ef ", raw).strip()


def _is_public_ip(ip: str) -> bool:
    try:
        addr = ipaddress.ip_address(ip)
        return not (addr.is_private or addr.is_loopback or addr.is_link_local or addr.is_reserved or addr.is_multicast)
    except ValueError:
        return False


def parse_albert_xlsx(content: bytes) -> tuple:
    """Returns (sheet_name, rows) -- rows is a list of raw dicts keyed by a fixed
    set of normalized keys, read from whichever columns are present by name (not
    position), so column reordering in a future CIS export format doesn't break
    this silently."""
    import openpyxl
    wb = openpyxl.load_workbook(io.BytesIO(content), read_only=True, data_only=True)
    if not wb.sheetnames:
        raise ValueError("This spreadsheet has no sheets")
    sheet_name = wb.sheetnames[0]
    ws = wb[sheet_name]

    rows_iter = ws.iter_rows(values_only=True)
    header = next(rows_iter, None)
    if not header:
        raise ValueError("This spreadsheet has no header row")
    header = [str(h).strip().upper() if h is not None else "" for h in header]

    missing = REQUIRED_COLUMNS - set(header)
    if missing:
        raise ValueError(
            f"This doesn't look like an Albert alert export -- missing column(s): {', '.join(sorted(missing))}"
        )

    idx = {name: pos for pos, name in enumerate(header) if name}
    rows = []
    for raw_row in rows_iter:
        raw_row = list(raw_row) + [None] * (len(header) - len(raw_row))

        def get(col):
            i = idx.get(col)
            return raw_row[i] if i is not None and i < len(raw_row) else None

        if get("TIME (GMT)") is None:
            continue
        rows.append({
            "time_gmt_raw": get("TIME (GMT)"), "device": get("DEVICE"),
            "alert_message": get("ALERT MESSAGE"), "source_ip": get("SOURCE IP"),
            "destination_ip": get("DESTINATION IP"), "source_port": get("SOURCE PORT"),
            "destination_port": get("DESTINATION PORT"), "protocol": get("PROTOCOL"),
            "stream_data": get("STREAM DATA"), "stream_data_length": get("STREAM DATA LENGTH"),
        })
    return sheet_name, rows


async def import_albert_export(db, content: bytes, filename: str, uploaded_by: Optional[str] = None) -> dict:
    sheet_name, raw_rows = parse_albert_xlsx(content)
    disposition = _infer_disposition(filename, sheet_name)

    from threat_intel_watchlist import check_and_emit
    from albert_allowlist import _allowlist_entries, suppression_reason

    allowlist_entries = await _allowlist_entries(db)

    docs = []
    skipped = 0
    times = []
    watchlist_matches = 0
    checked_ips = set()

    for raw in raw_rows:
        time_iso = _parse_time_gmt(raw["time_gmt_raw"])
        if not time_iso:
            skipped += 1
            continue
        times.append(time_iso)
        knowledge = _explain_alert(raw["alert_message"])
        protocol = raw["protocol"]
        try:
            protocol = int(protocol)
        except (TypeError, ValueError):
            protocol = None
        suppress_reason = suppression_reason(allowlist_entries, raw["source_ip"], raw["destination_ip"])
        suppressed = suppress_reason is not None
        doc = {
            "id": str(uuid.uuid4()), "time_gmt": time_iso, "device": raw["device"],
            "alert_message": raw["alert_message"], "category": knowledge["category"],
            "severity": knowledge["severity"], "explanation": knowledge["explanation"],
            "mitre_technique": knowledge["mitre_technique"],
            "source_ip": raw["source_ip"], "destination_ip": raw["destination_ip"],
            "source_port": raw["source_port"], "destination_port": raw["destination_port"],
            "protocol": protocol, "protocol_name": PROTOCOL_NAMES.get(protocol, str(protocol) if protocol else None),
            "stream_data": _clean_stream_data((raw["stream_data"] or "")[:2000]),
            "stream_data_raw": (raw["stream_data"] or "")[:2000], "stream_data_length": raw["stream_data_length"],
            "disposition": disposition, "imported_at": datetime.now(timezone.utc).isoformat(),
            "acknowledged": False, "suppressed": suppressed,
            "suppressed_reason": suppress_reason,
        }
        docs.append(doc)

    if docs:
        await db.albert_alerts.insert_many(docs)

    # Cross-check public source/destination IPs against the existing threat intel
    # watchlist -- "using external existing connections" the way the rest of the
    # platform already does for asset IPs and file hashes. Skipped for private/
    # internal IPs since those will never appear in a public IOC feed, and capped
    # to unique IPs seen in this batch so one huge import doesn't do redundant work.
    for doc in docs:
        for ip in (doc["source_ip"], doc["destination_ip"]):
            if not ip or ip in checked_ips or not _is_public_ip(ip):
                continue
            checked_ips.add(ip)
            match = await check_and_emit(
                db, ip, entity_type="albert_alert", entity_id=ip,
                entity_label=f"{ip} (seen in Albert alert: {doc['alert_message']})",
            )
            if match:
                watchlist_matches += 1

    record = {
        "id": str(uuid.uuid4()), "filename": filename, "sheet_name": sheet_name,
        "disposition": disposition, "rows_parsed": len(docs), "rows_skipped": skipped,
        "date_range_start": min(times) if times else None, "date_range_end": max(times) if times else None,
        "watchlist_matches": watchlist_matches, "uploaded_at": datetime.now(timezone.utc).isoformat(),
        "uploaded_by": uploaded_by,
    }
    await db.albert_imports.insert_one(record)

    severity_counts = {}
    dest_ip_counts = {}
    for d in docs:
        severity_counts[d["severity"]] = severity_counts.get(d["severity"], 0) + 1
        ip = d.get("destination_ip")
        if ip and _is_public_ip(ip):
            dest_ip_counts[ip] = dest_ip_counts.get(ip, 0) + 1
    top_public_destination_ips = [ip for ip, _ in sorted(dest_ip_counts.items(), key=lambda kv: -kv[1])]

    return {
        "import_id": record["id"], "rows_parsed": len(docs), "rows_skipped": skipped,
        "sheet_name": sheet_name, "disposition": disposition,
        "date_range_start": record["date_range_start"], "date_range_end": record["date_range_end"],
        "severity_counts": severity_counts, "watchlist_matches": watchlist_matches,
        "top_public_destination_ips": top_public_destination_ips,
    }


async def compute_albert_signatures(db, days: int = 90) -> list:
    """One row per distinct alert message seen in the last `days` -- the
    plain-English "what is this alert actually saying" reference the dashboard
    shows next to the raw counts, so an analyst doesn't have to go look up what a
    Suricata-style signature string means."""
    now = datetime.now(timezone.utc)
    cutoff = (now - timedelta(days=days)).isoformat()
    alerts = await db.albert_alerts.find(
        {"time_gmt": {"$gte": cutoff}},
        {"_id": 0, "alert_message": 1, "severity": 1, "category": 1, "explanation": 1, "mitre_technique": 1, "time_gmt": 1},
    ).to_list(200000)

    by_message = {}
    for a in alerts:
        msg = a.get("alert_message") or "(no message)"
        entry = by_message.setdefault(msg, {
            "alert_message": msg, "severity": a.get("severity"), "category": a.get("category"),
            "explanation": a.get("explanation"), "mitre_technique": a.get("mitre_technique"),
            "count": 0, "last_seen": a.get("time_gmt"),
        })
        entry["count"] += 1
        if a.get("time_gmt") and a["time_gmt"] > (entry["last_seen"] or ""):
            entry["last_seen"] = a["time_gmt"]

    _sev_rank = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
    return sorted(by_message.values(), key=lambda e: (_sev_rank.get(e["severity"], 9), -e["count"]))


async def compute_albert_sankey(db, days: int = 30) -> dict:
    """Device -> Category -> Severity flow for a Sankey diagram -- makes it easy
    to see at a glance which sensor is generating which kind of alert, and how
    severe those alerts skew, without reading three separate bar charts. Node
    names are namespaced by layer (dev:/cat:/sev:) internally to keep the three
    layers from colliding if a device and category ever happened to share a
    name, then given clean display labels."""
    now = datetime.now(timezone.utc)
    cutoff = (now - timedelta(days=days)).isoformat()
    alerts = await db.albert_alerts.find(
        {"time_gmt": {"$gte": cutoff}},
        {"_id": 0, "device": 1, "category": 1, "severity": 1},
    ).to_list(200000)

    dev_cat_counts, cat_sev_counts = {}, {}
    for a in alerts:
        dev, cat, sev = a.get("device") or "Unknown sensor", a.get("category") or "Uncategorized", a.get("severity") or "Medium"
        dev_cat_counts[(dev, cat)] = dev_cat_counts.get((dev, cat), 0) + 1
        cat_sev_counts[(cat, sev)] = cat_sev_counts.get((cat, sev), 0) + 1

    node_index = {}

    def _node(key, label):
        if key not in node_index:
            node_index[key] = len(node_index)
            nodes.append({"name": label})
        return node_index[key]

    nodes = []
    links = []
    for (dev, cat), count in sorted(dev_cat_counts.items(), key=lambda kv: -kv[1]):
        si = _node(f"dev:{dev}", dev)
        ti = _node(f"cat:{cat}", cat)
        links.append({"source": si, "target": ti, "value": count})
    for (cat, sev), count in sorted(cat_sev_counts.items(), key=lambda kv: -kv[1]):
        si = _node(f"cat:{cat}", cat)
        ti = _node(f"sev:{sev}", sev)
        links.append({"source": si, "target": ti, "value": count})

    return {"nodes": nodes, "links": links}


async def compute_albert_device_trend(db, days: int = 90) -> dict:
    """Longer-horizon per-device daily alert volume, independent of any single
    import batch -- compute_albert_stats' anomaly baseline compares a day against
    that (sensor, category) pair's own history, which flags spikes but doesn't
    answer "is this device's overall volume trending up over weeks/months". This
    aggregates unsuppressed alert counts by (day, device) across up to `days` of
    history so the frontend can plot one line per device and eyeball a slow climb
    that a single noisy day wouldn't trigger the anomaly check for."""
    now = datetime.now(timezone.utc)
    cutoff = (now - timedelta(days=days)).isoformat()
    alerts = await db.albert_alerts.find(
        {"time_gmt": {"$gte": cutoff}, "suppressed": {"$ne": True}},
        {"_id": 0, "device": 1, "time_gmt": 1},
    ).to_list(500000)

    daily_device_counts: dict = {}
    devices = set()
    for a in alerts:
        t = a.get("time_gmt")
        if not t:
            continue
        day = t[:10]
        dev = a.get("device") or "Unknown sensor"
        devices.add(dev)
        daily_device_counts[(day, dev)] = daily_device_counts.get((day, dev), 0) + 1

    days_sorted = sorted({d for d, _ in daily_device_counts})
    devices_sorted = sorted(devices)
    series = [
        {"date": day, **{dev: daily_device_counts.get((day, dev), 0) for dev in devices_sorted}}
        for day in days_sorted
    ]
    return {"series": series, "devices": devices_sorted}


async def compute_albert_stats(db, days: int = 30, include_suppressed: bool = False) -> dict:
    """Dashboard aggregates over the last `days` of ingested Albert alerts, plus a
    lightweight baseline check: for each (sensor, category) pair, compares each
    day's count in the requested range against the mean+stddev of that pair's
    daily counts across ALL stored history (not just the range), flagging days
    that spike well above normal. Grouping by sensor as well as category (not
    just category org-wide) means a single noisy sensor shows up even when the
    org-wide average for that category still looks normal. This is a simple
    statistical heuristic, not a certified anomaly detector -- it's meant to draw
    attention to "this is unusually high for this sensor+category," not to make
    a verdict on its own.

    Alerts matching the known-good allowlist (see albert_allowlist.py) are
    suppressed=True and excluded from these aggregates by default, the same way
    a SIEM lets you mute a known-noisy, known-good source without deleting the
    underlying events -- pass include_suppressed=True to include them anyway.
    """
    now = datetime.now(timezone.utc)
    cutoff = (now - timedelta(days=days)).isoformat()

    query = {} if include_suppressed else {"suppressed": {"$ne": True}}
    all_alerts = await db.albert_alerts.find(query, {
        "_id": 0, "time_gmt": 1, "severity": 1, "category": 1, "device": 1,
        "source_ip": 1, "destination_ip": 1, "disposition": 1,
    }).to_list(200000)
    suppressed_count = await db.albert_alerts.count_documents({"suppressed": True, "time_gmt": {"$gte": cutoff}})

    def _day(iso):
        return (iso or "")[:10]

    severity_counts, category_counts, device_counts = {}, {}, {}
    src_ip_counts, dst_ip_counts = {}, {}
    daily_counts = {}  # day -> count (within range)
    dev_cat_daily_all = {}  # (device, category) -> {day: count} across ALL history

    in_range_count = 0
    for a in all_alerts:
        day = _day(a.get("time_gmt"))
        cat = a.get("category") or "Uncategorized"
        dev = a.get("device") or "Unknown sensor"
        key = (dev, cat)
        dev_cat_daily_all.setdefault(key, {})
        dev_cat_daily_all[key][day] = dev_cat_daily_all[key].get(day, 0) + 1

        if a.get("time_gmt") and a["time_gmt"] >= cutoff:
            in_range_count += 1
            severity_counts[a.get("severity")] = severity_counts.get(a.get("severity"), 0) + 1
            category_counts[cat] = category_counts.get(cat, 0) + 1
            device_counts[dev] = device_counts.get(dev, 0) + 1
            if a.get("source_ip"):
                src_ip_counts[a["source_ip"]] = src_ip_counts.get(a["source_ip"], 0) + 1
            if a.get("destination_ip"):
                dst_ip_counts[a["destination_ip"]] = dst_ip_counts.get(a["destination_ip"], 0) + 1
            daily_counts[day] = daily_counts.get(day, 0) + 1

    def _mean_std(values):
        n = len(values)
        if n == 0:
            return 0.0, 0.0
        mean = sum(values) / n
        variance = sum((v - mean) ** 2 for v in values) / n
        return mean, variance ** 0.5

    anomalies = []
    range_days = {_day(a.get("time_gmt")) for a in all_alerts if a.get("time_gmt") and a["time_gmt"] >= cutoff}
    for (dev, cat), day_map in dev_cat_daily_all.items():
        mean, std = _mean_std(list(day_map.values()))
        threshold = mean + 2 * std
        for day in sorted(range_days):
            count = day_map.get(day, 0)
            if count > 0 and count > threshold and count > mean * 1.5 and threshold > 0:
                anomalies.append({
                    "day": day, "device": dev, "category": cat, "count": count,
                    "baseline_mean": round(mean, 1), "baseline_stddev": round(std, 1),
                })
    anomalies.sort(key=lambda x: x["day"], reverse=True)

    def _top(counter, n=10):
        return [{"value": k, "count": v} for k, v in sorted(counter.items(), key=lambda kv: -kv[1])[:n] if k]

    return {
        "range_days": days, "total_alerts": in_range_count, "suppressed_count": suppressed_count,
        "severity_counts": severity_counts, "category_counts": category_counts,
        "device_counts": device_counts,
        "daily_trend": [{"day": d, "count": c} for d, c in sorted(daily_counts.items())],
        "top_source_ips": _top(src_ip_counts), "top_destination_ips": _top(dst_ip_counts),
        "anomalies": anomalies[:20],
    }
