"""Shared PDF report styling -- a consistent page chrome (colored header band + footer
with page number, drawn on every page rather than just a one-off title paragraph on
page 1), stat-card and table helpers, and a single palette/type scale, so every report
generator (executive, compliance, aging, custom report builder) looks like the same
product instead of each hand-rolling its own reportlab boilerplate with the library's
bare defaults.

reportlab.graphics is a fairly basic vector chart toolkit -- this doesn't try to make
it look like a modern JS charting library, just applies one consistent, deliberately
chosen palette/typography instead of reportlab's stock black-Helvetica-on-white look.
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_RIGHT

INK = colors.HexColor("#0D1117")          # near-black page background band
PANEL = colors.HexColor("#161B22")
BORDER = colors.HexColor("#30363D")
ACCENT = colors.HexColor("#2F81F7")       # brand blue, matches the app's sidebar/links
TEXT = colors.HexColor("#1F2328")         # body text on white page background
MUTED = colors.HexColor("#57606A")
ROW_ALT = colors.HexColor("#F6F8FA")

SEVERITY_COLORS = {
    "Critical": colors.HexColor("#ef4444"), "High": colors.HexColor("#f97316"),
    "Medium": colors.HexColor("#f59e0b"), "Low": colors.HexColor("#3b82f6"),
    "Info": colors.HexColor("#64748b"),
}

HEADER_BAND_HEIGHT = 46
FOOTER_HEIGHT = 24


def get_styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("VOTitle", parent=base["Title"], fontName="Helvetica-Bold",
                                 fontSize=17, textColor=INK, spaceAfter=2, alignment=TA_LEFT),
        "subtitle": ParagraphStyle("VOSubtitle", parent=base["Normal"], fontName="Helvetica",
                                    fontSize=9.5, textColor=MUTED, spaceAfter=14),
        "h2": ParagraphStyle("VOH2", parent=base["Heading2"], fontName="Helvetica-Bold",
                              fontSize=12.5, textColor=INK, spaceBefore=14, spaceAfter=6),
        "h3": ParagraphStyle("VOH3", parent=base["Heading3"], fontName="Helvetica-Bold",
                              fontSize=10.5, textColor=INK, spaceBefore=10, spaceAfter=5),
        "body": ParagraphStyle("VOBody", parent=base["Normal"], fontName="Helvetica",
                                fontSize=9.5, textColor=TEXT, leading=13.5),
        "muted": ParagraphStyle("VOMuted", parent=base["Normal"], fontName="Helvetica-Oblique",
                                 fontSize=8.5, textColor=MUTED, leading=12),
        "bullet": ParagraphStyle("VOBullet", parent=base["Normal"], fontName="Helvetica",
                                  fontSize=9.5, textColor=TEXT, leading=14, leftIndent=10),
    }


def _draw_header_footer(canvas, doc, report_title: str):
    canvas.saveState()
    page_w, page_h = letter

    # Header band
    canvas.setFillColor(INK)
    canvas.rect(0, page_h - HEADER_BAND_HEIGHT, page_w, HEADER_BAND_HEIGHT, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 13)
    canvas.drawString(0.6 * inch, page_h - 29, "Nightwatch")
    canvas.setFillColor(ACCENT)
    canvas.setFont("Helvetica", 9)
    canvas.drawString(1.55 * inch, page_h - 28.5, report_title)
    canvas.setFillColor(colors.HexColor("#8B949E"))
    canvas.setFont("Helvetica", 7.5)
    canvas.drawRightString(page_w - 0.6 * inch, page_h - 28, "Vulnerability Operations")
    # thin accent rule under the band
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.4)
    canvas.line(0, page_h - HEADER_BAND_HEIGHT, page_w, page_h - HEADER_BAND_HEIGHT)

    # Footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(0.6 * inch, FOOTER_HEIGHT + 6, page_w - 0.6 * inch, FOOTER_HEIGHT + 6)
    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(0.6 * inch, FOOTER_HEIGHT - 4, "Generated by Nightwatch -- self-hosted security operations")
    canvas.drawRightString(page_w - 0.6 * inch, FOOTER_HEIGHT - 4, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def build_doc(buffer, report_title: str):
    """Returns (doc, elements) -- append flowables to `elements`, then call
    doc.build(elements). The header band + footer are drawn automatically on every
    page via onFirstPage/onLaterPages, so callers don't repeat that boilerplate."""
    def _on_page(canvas, doc):
        _draw_header_footer(canvas, doc, report_title)

    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=HEADER_BAND_HEIGHT + 22, bottomMargin=FOOTER_HEIGHT + 20,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
    )
    doc._vo_on_page = _on_page  # stashed for doc.build() callers below
    return doc, []


def build(doc, elements):
    """Thin wrapper around doc.build() that supplies the header/footer callback --
    keeps callers from needing to know about onFirstPage/onLaterPages at all."""
    doc.build(elements, onFirstPage=doc._vo_on_page, onLaterPages=doc._vo_on_page)


def stat_cards(items: list, width: float = 460) -> Table:
    """items: [{"label": "Security Score", "value": "82 / 100", "color": "#2F81F7"}, ...]
    Renders a row of bordered stat boxes -- used for top-of-report headline metrics
    instead of a stack of '<b>Label:</b> value' paragraphs."""
    n = len(items)
    col_w = width / n
    cells = []
    for it in items:
        color = colors.HexColor(it.get("color", "#2F81F7"))
        cells.append([
            Paragraph(str(it["value"]), ParagraphStyle(
                "cardval", fontName="Helvetica-Bold", fontSize=18, textColor=color, spaceAfter=1)),
            Paragraph(str(it["label"]).upper(), ParagraphStyle(
                "cardlbl", fontName="Helvetica", fontSize=7, textColor=MUTED, spaceAfter=0,
                leading=9)),
        ])
    t = Table([cells], colWidths=[col_w] * n)
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.75, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.75, BORDER),
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def styled_table(headers: list, rows: list, col_widths: list | None = None,
                  numeric_cols: tuple = (), width: float = 460) -> Table:
    """Consistent table look: dark header bar, zebra-striped body rows, light grid
    lines instead of reportlab's default heavy black borders."""
    data = [headers] + [[str(c) for c in r] for r in rows]
    t = Table(data, colWidths=col_widths, hAlign="LEFT", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("LINEBELOW", (0, 0), (-1, 0), 0.75, INK),
        ("LINEBELOW", (0, 1), (-1, -2), 0.4, colors.HexColor("#E5E9EE")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ("TEXTCOLOR", (0, 1), (-1, -1), TEXT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for col in numeric_cols:
        style.append(("ALIGN", (col, 0), (col, -1), "RIGHT"))
    t.setStyle(TableStyle(style))
    return t
